name: Run ERP Auto Download

on:
  schedule:
    - cron: '0 0,2,4,6,8,10 * * *'
  workflow_dispatch:

jobs:
  download-job:
    runs-on: ubuntu-latest

    steps:
    - name: "[GIAI DOAN 1/4] Lay ma nguon"
      uses: actions/checkout@v3

    - name: "[GIAI DOAN 2/4] Khoi tao moitruong Python"
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: "[GIAI DOAN 3/4] Cai dat thu vien"
      run: |
        pip install selenium webdriver-manager google-api-python-client google-auth-httplib2 google-auth-oauthlib

    - name: "[GIAI DOAN 4/4] Thuc thi Script Python & Upload Google Drive"
      env:
        ERP_USERNAME: ${{ secrets.ERP_USERNAME }}
        ERP_PASSWORD: ${{ secrets.ERP_PASSWORD }}
        GDRIVE_CREDENTIALS_JSON: ${{ secrets.GDRIVE_CREDENTIALS_JSON }}
        GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
      run: |
        python download_erp.py

    - name: "TU DONG LUU ANH MAN HINH VISUAL (DANG DEBUG)"
      if: always() # Luon xuat anh ngay ca khi code bi loi
      uses: actions/upload-artifact@v4
      with:
        name: Visual-Screenshots-Debug
        path: screenshots/
