name: Run ERP Auto Download

on:
  schedule:
    # Tự động chạy lúc 07:00 sáng giờ Việt Nam hàng ngày (00:00 UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Cho phép bấm nút chạy thủ công bất kỳ lúc nào

jobs:
  download-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install selenium webdriver-manager

    - name: Run Script
      run: |
        python download_erp.py

    - name: Upload Downloaded Files
      uses: actions/upload-artifact@v4
      with:
        name: Báo-Cáo-Tồn-Kho-Excel
        path: downloads/
